name: clean_flutter

description: A Clean Architecture Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
    sdk: ">=2.17.0 <3.0.0"

dependencies:
    flutter_svg: ^1.1.1+1

    google_fonts: ^3.0.1

    flutter_bloc: ^8.0.1

    cupertino_icons: ^1.0.2

    equatable: ^2.0.3

    flutter:
        sdk: flutter

    font_awesome_flutter: ^10.0.0

    get_it: ^7.2.0

    dartz: ^0.10.1

    dio: ^4.0.4

    hive: ^2.1.0

    hive_flutter: ^1.1.0

    path_provider: ^2.0.9

    go_router: ^4.2.5

    flutter_staggered_grid_view: ^0.6.2

    responsive_framework: ^0.2.0

    flex_color_scheme: ^5.1.0

    flutter_form_builder: ^7.5.0

    form_builder_validators: ^8.3.0

    custom_navigation_bar: ^0.8.2

    json_annotation: ^4.6.0

    adaptive_layout:
      path: packages/adaptive_layout

dev_dependencies:
    flutter_test:
        sdk: flutter

    build_runner: ^2.1.8

    injectable_generator: ^1.5.1

    flutter_lints: ^1.0.0

    mocktail: ^0.3.0

    bloc_test: ^9.0.3

    json_serializable: ^6.3.1

    http_mock_adapter: ^0.3.2

# The following section is specific to Flutter.
flutter:
    uses-material-design: true

    assets:
        - assets/images/
        - assets/svg/
        - assets/fonts/

    # To add assets to your application, add an assets section, like this:
    # assets:
    #   - images/a_dot_burr.jpeg
    #   - images/a_dot_ham.jpeg

    # example:
    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
