name: clean_flutter

description: A Clean Architecture Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
    sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter_svg: ^2.0.4
  google_fonts: ^4.0.3
  flutter_bloc: ^8.1.2
  cupertino_icons: ^1.0.5
  equatable: ^2.0.5
  flutter:
      sdk: flutter
  font_awesome_flutter: ^10.4.0
  get_it: ^7.2.0
  dio: ^5.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.14
  go_router: ^6.4.0
  flutter_staggered_grid_view: ^0.6.2
  responsive_framework: ^0.2.0
  flex_color_scheme: ^6.1.2
  flutter_form_builder: ^7.8.0
  form_builder_validators: ^8.5.0
  custom_navigation_bar: ^0.8.2
  json_annotation: ^4.8.0
  adaptive_layout:
      path: packages/adaptive_layout

dev_dependencies:
  flutter_test:
      sdk: flutter
  build_runner: ^2.1.8
  injectable_generator: ^1.5.1
  flutter_lints: ^1.0.0
  mocktail: ^0.3.0
  bloc_test: ^9.0.3
  json_serializable: ^6.3.1
  http_mock_adapter: ^0.4.2

# The following section is specific to Flutter.
flutter:
    uses-material-design: true

    assets:
        - assets/images/
        - assets/svg/
        - assets/fonts/
